<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Problemas Comuns <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>

            <div class="list-group col-sm-3">
                <?php foreach ($this->atividades as $item): ?>
                <a href="#" class="list-group-item active"><?php echo $item['nome'] ?></a>
                    <?php foreach ($this->atividades1 as $item1): ?>
                        <?php if ($item1['categoria_idcategoria'] == $item['idcategoria']){?>
                            <a href="/prob/interna/id/<?php echo $item1['idtipo'];?>" class="list-group-item"><?php echo $item1['nome'] ?></a>
                        <?php } ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>

            <div class="col-sm-9 TitulosPaginas">
                <div class="alert alert-warning TitulosPaginas" role="alert">
                    <p>Confira aqui os problemas de saúde mais recorrentes em animais de estimação.</p>
                </div>
            </div>




        </div>
    </div>

</section>