<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
       	<?php echo $this->headTitle(); ?>
        <link type="text/css" href="<?php echo $this->baseUrl("/static/intranet/bootstrap/css/bootstrap.min.css"); ?>" rel="StyleSheet" />
        <link type="text/css" href="<?php echo $this->baseUrl("/static/intranet/bootstrap/css/bootstrap-responsive.min.css"); ?>" rel="StyleSheet" />
        <link type="text/css" href="<?php echo $this->baseUrl("/static/intranet/css/intranet.css"); ?>" rel="StyleSheet" />
        <link type="text/css" href="<?php echo $this->baseUrl("/static/intranet/css/intranet.form.css"); ?>" rel="StyleSheet" />
        <link type="text/css" href="<?php echo $this->baseUrl("/global/jquery-ui/css/ui-lightness/jquery-ui-1.8.23.custom.css"); ?>" rel="StyleSheet" />
        <link type="text/css" href="<?php echo $this->baseUrl("/static/intranet/css/simple-sidebar.css"); ?>" rel="StyleSheet" />
        <script src="<?php echo $this->baseUrl("/static/tinymce/js/tinymce/tinymce.min.js"); ?>"></script>

    </head>
    <body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <?php if( $this->authStatus ): ?>
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#">
                            BabyCão
                        </a>
                    </li>
                    <li>
                        <a href="/admin/banner">Banner</a>
                    </li>
                    <li>
                        <a href="/admin/video">Videos</a>
                    </li>
                    <li>
                        <a href="/admin/servico">Serviços</a>
                    </li>
                    <li>
                        <a href="/admin/prob">Problemas Comuns</a>
                    </li>
                    <li>
                        <a href="/admin/ajuda">Ajuda</a>
                    </li>
                    <li>
                        <a href="/admin/petshop">Petshop</a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                    <a href="<?php echo $this->baseUrl('/admin/auth/logout'); ?>" class="btn">
                        <span class="icon-off"></span> Sair
                    </a>
                    </li>
                </ul>

            <?php endif; ?>
        </div>
        <!-- /#sidebar-wrapper -->



                    <?php echo $this->Layout()->content; ?>


        </div>

        <script type="text/javascript" src="<?php echo $this->baseUrl("/global/jquery-1.8.0.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("/static/intranet/bootstrap/js/bootstrap.min.js"); ?>"></script>

        <script src="<?php echo $this->baseUrl("/global/stringToSlug/jquery.stringToSlug.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("/global/ckeditor/ckeditor.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("/global/ckeditor/adapters/jquery.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("/static/intranet/js/intranet.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("/global/jquery-ui/js/jquery-ui-1.8.23.custom.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("/global/jquery-ui/development-bundle/ui/i18n/jquery.ui.datepicker-pt-BR.js"); ?>"></script>

    </body>
</html>
