<script>
	tinymce.init({
		selector: 'textarea',
		height: 200,
		plugins: [
			'advlist autolink lists link image charmap print preview anchor',
			'insertdatetime media table contextmenu paste code'
		],
		toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
	});
</script>
<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">

				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>SubCategoria Problemas</legend>

						<!-- Select Basic -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="categoria">categoria</label>
							<div class="col-md-4">
								<select id="categoria" name="categoria" class="form-control">

									<?php foreach ($this->atividades as $item): ?>
										<option value="<?php echo $item['idcategoria'] ?>"><?php echo $item['nome'] ?></option>
									<?php endforeach; ?>

								</select>
							</div>
						</div> <br>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" value = "<?php echo $this->atividades1['0']['nome'] ?>" class="form-control input-md">
								<input id="tipo" name="tipo" type="hidden" value="2" class="form-control input-md">
							</div>
						</div><br>

						<!-- Textarea -->
						<div class="form-group">
							<div class="col-md-4">
								<textarea  style="height: 30px; height: 30px" id="descricao" name="descricao"  rows="10" cols="10">&lt;p&gt;<?php echo $this->atividades1['0']['descricao'] ?>&lt;/p&gt;</textarea>

							</div>
						</div>
<br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
								<button type="submit" id="" name="" class="btn btn-primary">Enviar</button>
							</div>
						</div>

					</fieldset>
				</form>
			</div>

		</div>
	</div>
</div>