<div class="nav">
    <!--Header -->
    <header class="navbar-fixed-top animated fadeInDown">
        <div class="container">
            <div class="row">         
                <!-- Static navbar -->
                <div class="navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <h1 class="logo">
                            <a class="navbar-brand" href="#menu-jumbotron">
                            </a>
                        </h1> 

                    </div>
                    <div class="navbar-collapse collapse navbar-left">
                        <ul class="navbar-nav">
                            <li><a href="#menu-jumbotron">Início</a></li>
                            <li><a href="#menu-sobre">Sobre a prova</a></li>
                            <li><a href="#menu-cursos">Cursos</a> 
                                <!--<ul class="submenu">
                                    <li><i class="glyphicon glyphicon-ok"></i><a href="#" title="Sub Produto 1">Administração</a></li>
                                    <li><a href="#" title="Sub Produto 1">Biomedicina</a></li>
                                    <li><a href="#" title="Sub Produto 2">Enfermagem</a></li>
                                    <li><a href="#" title="Sub Produto 3">Farmácia</a></li>
                                    <li><a href="#" title="Sub Produto 3">Fisioterapia</a></li>
                                    <li><a href="#" title="Sub Produto 3">Nutrição</a></li>
                                    <li><a href="#" title="Sub Produto 3">Radiologia</a></li>

                                    <li><a href="#" title="Sub Produto 3">Serviço social</a></li>
                                    <li><a href="#" title="Sub Produto 3">Serviço social</a></li>
                                </ul>-->
                            </li>
                            <li><a href="#menu-video">Nova Uniamérica</a></li>
                            <li><a href="http://uniamerica.br/inscricoes/cadastro/37" class="external" target="blank_">Inscreva-se</a></li>
                            <li><a href="http://uniamerica.br/inscricoes/resultado/vestibular/id/37" class="external" target="blank_" style="color:red;">Resultado</a></li>
                            <li><a href="http://uniamerica.br/inscricoes/reimprimir/37" class="external" target="blank_" ><center>Reimprimir<br/>boleto</center></a></li>
                            <!--<li><a href="#menu-video">Vídeo</a></li>
                            <li><a href="#menu-information">Projetos</a></li>-->

                        </ul>
                    </div><!--/.nav-collapse -->

                    <!-- box_social -->
                    <div class="box_social">
                        <div class="fb-share-button" data-href="http://uniamerica.br/vestibulardebolsas" data-type="box_count" style="margin-right: 5px; border:none; overflow:hidden;"></div>
                    </div>
                    <!-- end box_social -->
                    <div class="chat" style="float: right; margin-right: 20px;margin-top: 5px;">
                        <!-- mibew button --><a href="http://chat.uniamerica.br/client.php?locale=pt-br&amp;style=silver" target="_blank" onclick="if(navigator.userAgent.toLowerCase().indexOf('opera') != -1 &amp;&amp; window.event.preventDefault) window.event.preventDefault();this.newWindow = window.open(&#039;http://chat.uniamerica.br/client.php?locale=pt-br&amp;url=&#039;+escape(document.location.href)+&#039;&amp;referrer=&#039;+escape(document.referrer), 'mibew', 'toolbar=0,scrollbars=0,location=0,status=1,menubar=0,width=640,height=480,resizable=1');this.newWindow.focus();this.newWindow.opener=window;return false;"><img src="http://chat.uniamerica.br/b.php?i=mgreen&amp;lang=pt-br" border="0" width="177" height="61" alt=""/>
                            <p style="font-size: 9px;">Atendimento das 08h00 às 21h00</p></a><!-- / mibew button -->
                    </div>
                </div>
                <!-- end container -->  


                </header>
                <!-- end Header -->

                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog" style="width: 80%;">
                        <div class="modal-content">
                            <div class="modal-header" style="padding: 0;">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h2 class="modal-title">BOLSAS DE ESTUDO</h2>
                                <p>A Faculdade União das Américas concede Bolsas de Estudo integrais para cursos de graduação: Ciências Biológicas e Farmácia, a estudantes sem diploma de nível superior, seguindo critérios socioeconômicos predefinidos e levando em consideração a classificação do candidato no Vestibular.</p>
                            </div>
                            <div class="row">
                                <h4>QUEM PODE CONCORRER?</h4>
                                <p>Estudantes sem diploma de nível superior (calouros) e com renda familiar bruta, por pessoa, de até um salário mínimo e meio.<br />
                                    Estudantes matriculados em cursos de graduação e que não tenham diploma de conclusão de curso superior (veteranos) com renda familiar bruta, por pessoa, de até um salário mínimo e meio.<br />
                                    Não serão aceitos candidatos que já tenham concluído um curso superior .
                                </p>
                                <h4>QUANTAS BOLSAS SERÃO OFERTADAS?</h4>
                                <p>30 bolsas integrais.</p>
                                <h4>COMO FUNCIONA? </h4>
                                <p>O candidato interessado em solicitar Bolsa de Estudo deve inscrever-se normalmente para participar no Vestibular. Tendo ciência de que deve comprovar renda familiar dentro dos limites estabelecidos no concurso de Bolsa. A inscrição é feita pela internet, clicando no botão INSCREVA-SE.
                                    Os candidatos melhores classificados no Vestibular serão convocados para uma entrevista com a equipe do Serviço Social da Uniamérica, devendo apresentar toda a documentação necessária à comprovação da sua situação socioeconômica, justificando o pedido da Bolsa.
                                    Para certificar-se da veracidade das informações prestadas, a instituição pode solicitar ao estudante todos os documentos que julgar necessários, dentro dos limites estabelecidos pela Lei.
                                </p>
                                <h4> É PRECISO FAZER O VESTIBULAR PARA CONCORRER A UMA BOLSA?</h4>
                                <p>Sim, é necessária a participação e a aprovação no Vestibular.</p>
                                <h4>CANDIDATO QUE POSSUI GRADUAÇÃO SUPERIOR COMPLETA PODE CONCORRER A BOLSA?</h4>
                                <p>Não. As bolsas de estudos se destinam a candidatos SEM diploma de nível superior.</p>
                                <h4>HÁ UMA DATA ESPECÍFICA PARA O VESTIBULAR DOS CANDIDATOS QUE QUEREM SOLICITAR BOLSA?</h4>
                                <p>Sim, dia 05/07/2014.</p>
                                <h4>COMO FAZER A INSCRIÇÃO CASO O CANDIDATO NÃO POSSUA ACESSO A INTERNET?</h4>
                                <p>Os candidatos poderão fazer a sua inscrição, presencialmente, na Central de Atendimento da Uniamérica.</p>
                                <h4>COMO CALCULAR A RENDA FAMILIAR BRUTA MENSAL POR PESSOA? </h4>
                                <p>A renda é calculada somando-se a renda bruta mensal dos componentes do grupo familiar e dividindo-se pelo número de pessoas que formam este grupo familiar. Se o resultado for até um salário mínimo e meio, o estudante poderá concorrer a uma bolsa integral.</p>
                                <h4>QUAL É A DOCUMENTAÇÃO QUE DEVE SER APRESENTADA PARA COMPROVAÇÃO DA SITUAÇÃO SOCIOECONÔMICA?</h4>
                                <p>Consulte o Edital.</p><br />
                                <p><a href="/static/vestibulardebolsas/edital/edital_201405.pdf" class="external green btn scroll_btn" target="blank_">Edital</a> <a href="http://uniamerica.br/inscricoes/cadastro/37" target="blank_" class="btn btn-default external">Inscreva-se</a></p>

                            </div>


                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->

                <!-- Master Wrap : ends -->
                <section class="jumbotron animated fadeInUp delay2" id="menu-jumbotron">
                    <div class="container"> 
                        <div class="row">
                            <div class="col-md-6 text-left valign animated fadeInUp  delay3">
                                <img src="/static/vestibulardebolsas/big-image.png" alt="image" class="figure">
                            </div>
                            <!-- <div class="col-md-6 bg-opacity">                
                                 <h2>O Vestibular de Bolsas Uniamérica</h2>
                                 <p style="text-align: justify;">O Intensivão da Uniamérica é dedicado a quem está se preparando para o ENEM e para o Vestibular de Bolsas Uniamérica. Através dele, você revisa os conteúdos essenciais, conta com a resolução de questões das grandes áreas do conhecimento e fica mais perto de conquistar seus objetivos. Ainda, pode contar com palestras de especialistas sobre assuntos específicos que focam o sucesso nas provas.</p>
                                 <p style="text-align: center;">
                                     <a class="btn text-center" target="blank_" href="href="http://uniamerica.br/inscricoes/cadastro/37"">Inscreva-se!</a>
                                 </p>
                             </div>-->
                        </div>   
                    </div>
                </section>
                <!-- end slider -->
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 vertical_line text-center">
                            <a href="#myModal"  class="btn green btn-default" data-toggle="modal">Sobre a bolsa</a> <a href="http://uniamerica.br/inscricoes/cadastro/37" class="external btn scroll_btn" target="blank_">Inscreva-se!</a>    
                        </div>
                    </div>
                </div>
                <section id="menu-sobre" class="generic features   animated fadeInUp delay2 space" style="background:none; border: none;">
                    <div class="container">
                        <div class="row text-center title">
                            <h1>Sobre a Prova </h1>
                            <h2>Uniamérica aposta na Educação com o “Vestibular de Bolsas”</h2>

                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <h1 style="font-size:6em; text-transform: uppercase; text-shadow: 1px 1px 3px #000; color: #007922; font-weight: bold;">Sobre a Bolsa</h1>
                                <p>A Faculdade União das Américas concede “Bolsas de Estudo Integrais” para cursos de graduação (Farmácia e Ciências Biológicas), a estudantes sem diploma de nível superior, seguindo critérios socioeconômicos predefinidos e levando em consideração a classificação do candidato no vestibular. Um investimento na Educação.</p>                               <!--<p><strong>Inscrições até 04/07/2014</strong></p>
                                                                    <p><strong>Horário:</strong> 14h às 18h</p> -->
                                <p><strong>Resultado:</strong> 10/07/2014 após as 14h no site da Uniamérica.</p>
                                <p><strong>Entrevista Sócio Econômica:</strong> 11/07/2014 e 12/07/2014</p>
                                <p><strong>Matrícula:</strong> 14/07/2014 à 18/07/2014</p>

                                <p><strong>Local:</strong> Uniamérica</p>
                                <p>Avenida Tarquínio Joslin dos Santos, 1000 – Jd.  Universitário – Foz do Iguaçu/PR</p>
                                <p><strong>Taxa de inscrição:</strong> R$ 20,00 (vinte reais)</p>
                                <a href="#myModal"  class="btn green btn-default" data-toggle="modal">Sobre a Bolsa</a> <a href="/static/vestibulardebolsas/edital/edital_201405.pdf" class="external green btn scroll_btn" target="blank_">Consultar o Edital</a> <a href="http://uniamerica.br/inscricoes/cadastro/37" class="external btn scroll_btn" target="blank_">Inscreva-se!</a>
                            </div>
                            <div class="col-md-6">
                                <iframe style="width: 100%; height: 320px;" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.br/maps?f=q&amp;source=s_q&amp;hl=pt&amp;geocode=&amp;q=Faculdade+Uni%C3%A3o+das+Am%C3%A9ricas+-+Avenida+Tarqu%C3%ADnio+Joslin+dos+Santos,+Foz+do+Igua%C3%A7u+-+PR&amp;aq=0&amp;oq=faculdade+unia&amp;sll=-3.765704,-38.590416&amp;sspn=0.008821,0.013937&amp;ie=UTF8&amp;hq=&amp;hnear=&amp;ll=-25.464475,-54.573007&amp;spn=0.006295,0.006295&amp;t=m&amp;output=embed"></iframe>
                            </div>

                        </div>

                </section>

                <section id="menu-cursos" class="generic classes  animated fadeInUp delay2">
                    <div class="container">


                        <!-- title -->
                        <div class="row text-center title">
                            <h1>Cursos</h1>
                            <h2 style="color:#000;">  </h2>
                        </div>
                        <!-- end title -->

                        <div class="row">

                            <!-- table 1 -->
                            <div class="col-md-3">
                                <div class="item">
                                    <div class="ch-item ch-img-1 thumb">
                                        <a href="#menu-educacao">
                                            <div class="ch-info">
                                                <p>Educação</p>
                                            </div>
                                        </a>
                                    </div>
                                    <ul>
                                        <a href="#curso-ed-fisica-l"><li><i class="glyphicon glyphicon-ok"></i> Educação Física (Licenciatura)</li></a>
                                        <a href="#curso-biologicas"><li><i class="glyphicon glyphicon-ok"></i> Ciências Biológicas (Licenciatura)</li></a>
                                        <a href="#curso-historia"><li><i class="glyphicon glyphicon-ok"></i> História </li></a>
                                        <a href="#curso-pedagogia"><li><i class="glyphicon glyphicon-ok"></i> Pedagogia</li></a>
                                    </ul> 
                                </div>
                            </div>

                            <!-- table 2 -->
                            <div class="col-md-3">
                                <div class="item">
                                    <div class="ch-item ch-img-2 thumb">
                                        <a href="#menu-engenharia"><div class="ch-info">
                                                <p>Arquitetura e Engenharias</p>
                                            </div>
                                        </a>
                                    </div>
                                    <ul>
                                        <a href="#curso-arquitetura"><li><i class="glyphicon glyphicon-ok"></i>  Arquitetura e Urbanismo</li></a>
                                        <a href="#curso-eg-ambiental"><li><i class="glyphicon glyphicon-ok"></i>  Engenharia Ambiental</li></a>
                                        <a href="#curso-eg-civil"><li><i class="glyphicon glyphicon-ok"></i> Engenharia Civil </li></a>
                                        <a href="#curso-eg-produção"><li><i class="glyphicon glyphicon-ok"></i> Engenharia de Produção </li></a>
                                    </ul> 
                                </div>
                            </div>

                            <!-- table 3 -->
                            <div class="col-md-3">
                                <div class="item">
                                    <div class="ch-item ch-img-3 thumb">
                                        <a href="#menu-saude">
                                            <div class="ch-info">
                                                <p> Saúde </p>
                                            </div>
                                        </a>
                                    </div>
                                    <ul>
                                        <a href="#curso-biomedicina"><li><i class="glyphicon glyphicon-ok"></i> Biomedicina</li></a>
                                        <a href="#curso-biologicas-b"><li><i class="glyphicon glyphicon-ok"></i> Ciências Biológicas (Bacharelado)</li></a>
                                        <a href="#curso-ed-fisica"><li><i class="glyphicon glyphicon-ok"></i> Educação Física (Bacharelado) </li></a>
                                        <a href="#curso-enfermagem"><li><i class="glyphicon glyphicon-ok"></i> Enfermagem </li></a>
                                        <a href="#curso-farmacia"><li><i class="glyphicon glyphicon-ok"></i> Farmácia</li></a>
                                        <a href="#curso-fisioterapia"><li><i class="glyphicon glyphicon-ok"></i> Fisioterapia </li></a>
                                        <a href="#curso-nutricao"><li><i class="glyphicon glyphicon-ok"></i> Nutrição </li></a>
                                        <a href="#curso-psicologia"><li><i class="glyphicon glyphicon-ok"></i> Psicologia </li></a>
                                        <a href="#curso-radiologia"><li><i class="glyphicon glyphicon-ok"></i> Radiologia </li></a>
                                    </ul> 
                                </div>
                            </div>

                            <!-- table 4 -->
                            <div class="col-md-3">
                                <div class="item">
                                    <div class="ch-item ch-img-4 thumb">
                                        <a href="#menu-negocios">
                                            <div class="ch-info">
                                                <p>Negócios e <br /> Ciências Sociais </p>
                                            </div>
                                        </a>
                                    </div>
                                    <ul>
                                        <a href="#curso-administracao"><li><i class="glyphicon glyphicon-ok"></i> Administração</li></a>
                                        <a href="#curso-contabeis"><li><i class="glyphicon glyphicon-ok"></i> Ciências Contábeis </li></a>
                                        <a href="#curso-gastronomia"><li><i class="glyphicon glyphicon-ok"></i> Gastronomia </li></a>
                                        <a href="#curso-social"><li><i class="glyphicon glyphicon-ok"></i> Serviço Social </li></a>
                                    </ul> 
                                </div>
                            </div>
                        </div> <!-- end row --> 
                        <div class="row">
                            <div class="col-xs-12 vertical_line text-center">
                                <a href="#myModal"  class="btn green btn-default" data-toggle="modal">Mensalidade</a> <a href="http://uniamerica.br/inscricoes/cadastro/37" class="external btn scroll_btn" target="blank_">Inscreva-se!</a>    
                            </div>
                        </div>
                    </div>
                </section> 

                <!--<section id="menu-cursos" class="generic info gallery cs-style-3 info  animated fadeInUp delay3" style="padding-bottom: 10px;">
                    <div class="container">


                        <div class="row text-center title">
                            <h1>Cursos</h1>
                        </div>


                        <div  id="curso-biologicas" class="row infocurso infoitem curso animated fadeInUp delay3">
                            <div class="col-md-8">
                                <h2>Ciências Biológicas (Licenciatura)</h2>
                                <span style="font-size: 15px;"><strong>Duração mínima:</strong> 7 semestres <strong>Turno:</strong> Noturno <strong>Formação:</strong> Licenciatura</span>
                                <div class="cur_desc">
                                    <h3>O curso estuda os seres vivos, a relação entre eles e o ambiente, construindo conhecimento sobre os processos e mecanismos que regulam a vida.
                                        o estudante deixa a postura passiva de somente assistir aulas, para uma postura participativa.  Todo o conteúdo de aula está disponível para o aluno no 
                                        ambiente virtual de aprendizagem. Ele estuda onde estiver e vem para a sala de aula trocar ideias com os colegas e realizar projetos de pesquisa sob a 
                                        orientação do Professor.  </h3>
                                    <h4>Área de atuação</h4> 
                                    <p>Meio Ambiente, Saúde, Educação e Biotecnologia e Produção. E cada uma delas possui áreas 
                                        específicas, como exemplo de gerenciamento de parques, zoológicos ou unidades de conservação, gestão de museus, licenciamento ambiental, produção de vacinas, controle de pragas e vetores, 
                                        genética, biotecnologia, saúde pública, microbiologia, pesquisa em instituições de ensino superior, empresas e laboratórios de pesquisa científica e tecnológica.</p>

                                    <h4>Diferenciais do Curso</h4>
                                    <p>É o primeiro Curso de Ciências Biológicas do Brasil a utilizar a metodologia de aprendizagem ativa,  que antecipa, desde o primeiro semestre do curso, o contato direto com situações reais que vai encontrar na sua profissão depois de formado;</p>
                                    <p>O aluno tem acesso há mais de 200 vídeos por semestre, com conteúdos complementares e necessários para ele realizar as aulas e projetos;</p>
                                    <p>Os alunos recebem a formação em Empreendedorismo que orienta a pensar grande, inovar, quebrar paradigmas e colocar paixão no que fazem;</p>
                                    <p>A sala de aula é um ambiente inovador, com mesas de trabalho, sofás, puffs, televisores, projetores, quadros e telas para uso em conjunto com diversos grupos de trabalho;</p>
                                    <p>O curso de Ciências biológicas oferece duas opções de habilitação, a licenciatura (ensino e pesquisa) e o bacharelado (pesquisa e consultoria ambiental);</p>
                                    <p>Os alunos possuem acesso irrestrito a uma biblioteca virtual, com acervo de mais de 5.400 títulos. É como se o estudante carregasse na mochila 5.400 livros.</p>
                                </div>
                                <a href="http://uniamerica.br/inscricoes/cadastro/37" class="btn scroll_btn external" target="blank_">Inscreva-se!</a>    
                            </div>
                            <div class="col-md-4">
                                <figure>
                                    <img src="/static/vestibular/img/cursos/18.jpg" alt="Curso de Ciências Biológicas ">
                                    <figcaption class="text-center">
                                        <h3>Ciências Biológicas </h3>
                                        <h4>Licenciatura</h4>
                                        <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2FFaculdadeUniamerica&amp;width&amp;layout=button&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=35&amp;appId=637345663027229" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:35px; margin-left: 40%;" allowTransparency="true"></iframe>              
                                    </figcaption>
                                </figure>
                            </div>
                        </div>

                        <div  id="curso-biologicas-b" class="row infocurso infoitem curso animated fadeInUp delay3">
                            <div class="col-md-4">
                                <figure>
                                    <img src="/static/vestibular/img/cursos/02.jpg" alt="Curso de Ciências Biológicas ">
                                    <figcaption class="text-center">
                                        <h3>Ciências Biológicas </h3>
                                        <h4>Bacharelado</h4>
                                        <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2FFaculdadeUniamerica&amp;width&amp;layout=button&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=35&amp;appId=637345663027229" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:35px; margin-left: 40%;" allowTransparency="true"></iframe>              
                                    </figcaption>
                                </figure>
                            </div>
                            <div class="col-md-8">
                                <h2>Ciências Biológicas (Bacharelado)</h2>
                                <span style="font-size: 15px;"><strong>Duração mínima:</strong> 8 semestres <strong>Turno:</strong> Noturno <strong>Formação:</strong> Bacharelado</span>
                                <div class="cur_desc">
                                    <h3>O curso estuda os seres vivos, a relação entre eles e o ambiente, construindo conhecimento sobre os processos e mecanismos que regulam a vida.
                                        o estudante deixa a postura passiva de somente assistir aulas, para uma postura participativa.  Todo o conteúdo de aula está disponível para o aluno no 
                                        ambiente virtual de aprendizagem. Ele estuda onde estiver e vem para a sala de aula trocar ideias com os colegas e realizar projetos de pesquisa sob a 
                                        orientação do Professor.  </h3>
                                    <h4>Área de atuação</h4> 
                                    <p>Meio Ambiente, Saúde, Educação e Biotecnologia e Produção. E cada uma delas possui áreas 
                                        específicas, como exemplo de gerenciamento de parques, zoológicos ou unidades de conservação, gestão de museus, licenciamento ambiental, produção de vacinas, controle de pragas e vetores, 
                                        genética, biotecnologia, saúde pública, microbiologia, pesquisa em instituições de ensino superior, empresas e laboratórios de pesquisa científica e tecnológica.</p>

                                    <h4>Diferenciais do Curso</h4>
                                    <p>É o primeiro Curso de Ciências Biológicas do Brasil a utilizar a metodologia de aprendizagem ativa,  que antecipa, desde o primeiro semestre do curso, o contato direto com situações reais que vai encontrar na sua profissão depois de formado;</p>
                                    <p>O aluno tem acesso há mais de 200 vídeos por semestre, com conteúdos complementares e necessários para ele realizar as aulas e projetos;</p>
                                    <p>Os alunos recebem a formação em Empreendedorismo que orienta a pensar grande, inovar, quebrar paradigmas e colocar paixão no que fazem;</p>
                                    <p>A sala de aula é um ambiente inovador, com mesas de trabalho, sofás, puffs, televisores, projetores, quadros e telas para uso em conjunto com diversos grupos de trabalho;</p>
                                    <p>Os alunos possuem acesso irrestrito a uma biblioteca virtual, com acervo de mais de 5.400 títulos. É como se o estudante carregasse na mochila 5.400 livros.</p>
                                </div>
                                <a href="http://uniamerica.br/inscricoes/cadastro/37" class="btn scroll_btn external" target="blank_">Inscreva-se!</a>     
                            </div>

                        </div>




                        <div id="curso-farmacia" class="row infocurso infoitem curso animated fadeInUp delay3">
                            <div class="col-md-8">
                                <h2>Farmácia</h2>
                                <span style="font-size: 15px;"><strong>Duração mínima:</strong> 10 semestres <strong>Turno:</strong> Noturno <strong>Formação:</strong> Bacharelado</span>
                                <div class="cur_desc">
                                    <p></p>
                                    <h3>O curso da Uniamérica visa à formação do profissional farmacêutico com um perfil generalista, com formação técnica científica, com visão humanista, crítica, reflexiva e ética para o exercício de sua carreira, visando melhorar a qualidade de vida dos pacientes.
                                        Na Uniamérica, o estudante de Farmácia deixa a postura passiva de somente assistir aulas, para uma postura participativa.  Todo o conteúdo de aula está disponível para o aluno no ambiente virtual de aprendizagem. Ele estuda onde estiver e vem para a sala de aula trocar ideias com os colegas e recebe orientação do Professor. 
                                    </h3>
                                    <h4>Áreas de atuação</h4>
                                    <p>Administração de farmácias em geral, serviço público, laboratório clínico, laboratórios farmacêuticos, farmácia hospitalar, farmácia de manipulação e homeopatia, Fitoterapia, indústria farmacêutica, indústria de cosméticos, logística e transporte de medicamentos, indústria de alimentos, 
                                        laboratório de análises clínicas, auditoria farmacêutica, Vigilância sanitária, Biofarmácia, Biologia molecular, Bioquímica clínica, Citologia clínica, Citopatologia, Citoquímica, Exames de DNA, 
                                        Farmacocinética clínica, Farmacoepidemiologia, Farmacogenética e Genética humana, Hematologia clínica, Micologia clínica, Microbiologia clínica, Nutrição parenteral, 
                                        Parasitologia clínica, Saúde pública, Toxicologia, Virologia clínica, entre outras.</p>

                                    <h4>Diferenciais do Curso</h4>
                                    <p>É o primeiro Curso de Farmácia do Brasil a utilizar a metodologia de aprendizagem ativa, que antecipa, desde o primeiro semestre do curso, o contato direto com situações reais que vai encontrar na sua profissão depois de formado;</p>
                                    <p>Os alunos têm como eixo transversal o Empreendedorismo que orienta a pensar grande, inovar, quebrar paradigmas e colocar paixão no que fazem;</p>
                                    <p>A sala de aula é um ambiente inovador, com mesas de trabalho, sofás, puffs, televisores, projetores, quadros e telas para uso concomitante de diversos grupos de trabalho;</p>
                                    <p>O aluno tem acesso há mais de 200 vídeos por semestre, com conteúdos complementares e necessários para ele realizar seus projetos;</p>
                                    <p>Os alunos possuem acesso irrestrito a uma biblioteca virtual, com acervo de mais de 5.400 títulos. É como se o estudante carregasse na mochila 5.400 livros.</p>
                                </div>
                                <a href="http://uniamerica.br/inscricoes/cadastro/37" class="btn scroll_btn external" target="blank_">Inscreva-se!</a>     
                            </div>
                            <div class="col-md-4">
                                <figure>
                                    <img src="/static/vestibular/img/cursos/11.jpg" alt="Curso de Farmácia ">
                                    <figcaption class="text-center">
                                        <h3> Farmácia </h3>
                                        <h4>Bacharelado</h4>
                                        <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2FFaculdadeUniamerica&amp;width&amp;layout=button&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=35&amp;appId=637345663027229" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:35px; margin-left: 40%;" allowTransparency="true"></iframe>              
                                    </figcaption>
                                </figure>
                            </div>
                        </div>
                    </div>
                </section>-->  
                <!-- end negocios e ciencias -->
                <!-- Space -->
                <section id="menu-video" class="space generic animated fadeInUp delay3">   
                    <div class="container">
                        <div class="row">
                            <!-- title -->
                            <div class="row text-center title">
                                <h1>A Nova Uniamérica</h1>
                                <h2></h2>
                            </div>
                            <!-- end title -->
                            <div class="col-md-4">
                                <h1>Metodologia de Ensino</h1>
                                <p>A Uniamérica utiliza em seus cursos de Graduação, uma metodologia de aprendizagem semelhante a utilizada nas Universidades de Harvard, MIT e Stanford (as melhores do mundo) que tem como base os seguintes princípios:</p>
                                <ul>
                                    <li><a href="#menu-video"> <i class="glyphicon glyphicon-ok"></i>Active Learning Classroom: Sala de aula colaborativa, onde os alunos participam de atividades em grupo e de estudos individuais.</a> </li>
                                    <li><a href="#menu-video"> <i class="glyphicon glyphicon-ok"></i>Blended Learning: O estudante pode acessar todo o conteúdo do seu curso de forma online, para estudar onde quiser e na hora que quiser. </a> </li>
                                    <li><a href="#menu-video"> <i class="glyphicon glyphicon-ok"></i>Mobile Learning: Conteúdo disponibilizado em todos os dispositivos móveis.</a> </li>
                                    <li><a href="#menu-video"> <i class="glyphicon glyphicon-ok"></i>Crowdsourcing: Método de aprendizagem colaborativa, estruturado para resolução de problemas reais.</a> </li>
                                </ul>   
                            </div>
                            <div class="col-md-8">
                                <div class="video">
                                    <div class="fluid-width-video-wrapper" style="padding-top: 56.666666666666664%;">

                                        <iframe height="400" src="//www.youtube.com/embed/S6j3tq9R_MI?rel=0" frameborder="0" allowfullscreen></iframe>

                                    </div>
                                </div>        
                            </div>

                        </div>
                    </div>      
                </section>
                <!-- end Space -->
                <!--Wall Gallery-->
                <section class="wall generic" id="menu-wall">   
                    <div class="row">

                        <div class="col-sm-12">
                            <div id="ri-grid" class="ri-grid ri-grid-size-2">
                                <img class="ri-loading-image" src="/static/vestibular/img/loading.gif" alt="//">
                                <ul>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/1.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/2.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/3.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/4.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/5.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/6.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/7.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/8.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/9.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/10.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/11.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/12.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/13.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/14.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/15.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/16.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/17.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/18.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/19.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/20.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/21.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/22.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/23.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/24.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/25.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/26.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/27.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/28.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/29.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/30.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/31.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/32.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/33.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/34.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/35.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/36.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/37.jpg" alt="//"></a></li>
                                    <li><a href="#"><img src="/static/vestibulardebolsas/img/medium/38.jpg" alt="//"></a></li>
                                </ul>

                            </div>
                        </div>
                    </div>

                </section>
                <!-- End Wall Gallery-->

                <!-- Projetos uniamerica -->
                <section id="menu-information" class="generic info  animated fadeInUp delay3">
                    <div class="container">

                        <!-- title -->
                        <div class="row text-center title">
                            <h1>Os Novos Projetos da Uniamérica</h1>
                            <h2></h2>
                        </div>
                        <!-- end title -->

                        <div class="row infoitem">
                            <div class="col-md-6">
                                <img src="/static/vestibular/info-01.jpg" alt="image">
                            </div>
                            <div class="col-md-6">
                                <h2>Incubadora de empresas</h2>
                                <h3>A incubadora e aceleradora de empresas da Uniamérica é o lugar certo para:</h3>
                                <p>Tem um plano de negócio pronto e precisa de auxílio ou investimento para materializá-lo.</p>
                                <p>Tem um bom projeto, que precisa converter em plano de negócio.</p>
                                <p>Tem apenas uma boa ideia e precisa saber se ela é viável.</p>
                                <p>Já tem uma empresa, mas precisa acelerar seu desenvolvimento.</p>
                            </div>
                        </div>

                        <div class="row infoitem">
                            <div class="col-md-6">
                                <h2>Coworking Uniamérica</h2>
                                <h3>Espaço destinado a receber profissionais que estejam começando suas atividades e necessitem de um espaço de trabalho compartilhado, tendo a oportunidade de criar uma ampla rede de contatos que impulsione suas carreiras e tragam novos horizontes e perspectivas de negócios.</h3>
                                <p>Ex-alunos formados da Uniamérica e demais colegas profissionais, encontrarão em nosso Coworking mais do que um espaço de trabalho, um verdadeiro ambiente de inovação, criativdade e oportunidades profissionais que irão acelear intensamente o desenvolvimento de suas carreiras.</p>
                            </div>
                            <div class="col-md-6">
                                <img src="/static/vestibulardebolsas/info-03.jpg" alt="image">
                            </div>
                        </div>

                        <div class="row infoitem">
                            <div class="col-md-6">
                                <a target="blank_" href="http://uniamerica.br/languagecenter/"> <img src="/static/vestibulardebolsas/info-02.jpg" alt="image"></a>
                            </div>
                            <div class="col-md-6">
                                <h2>Language Center Uniamérica</h2>
                                <h3>Unidade de aprendizagem do idiomas de Inglês para crianças e adultos, contando com professores doutores do quadro docente da Uniamérica e utilizando metodologia moderna e material didático diferenciado.</h3>
                                <p> O Centro de Idiomas oferecerá também o curso de português para estrangeiros.</p>
                                <a  target="blank_" class="btn green btn-default external" href="http://uniamerica.br/languagecenter/">Conheça!</a>
                            </div>
                        </div> 
                        <!-- title -->
                        <div class="row text-center title">
                            <h1>Amigos da Uniamérica</h1>
                        </div>
                        <!-- end title -->
                        <div class="row infoitem">
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/anima-educacao.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/evolui.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/instituto-pninsula.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/hoper.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/livre-pensamento.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/trafor.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/mackenzie.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/puc.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/endeavor.jpg"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/itaipu.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/una.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/pti.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/editora-saraiva.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/bertoni.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/unioeste.png"></div>
                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/unibh.png"></div>

                            <div class="col-md-1">
                                <img src="/static/vestibular/img/parceiros/anhembi.png"></div>


                        </div>

                    </div>
                </section>  
                <!-- end projetos uniamerica -->
            </div>
