<script>
	tinymce.init({
		selector: 'textarea',
		height: 200,
		plugins: [
			'advlist autolink lists link image charmap print preview anchor',
			'insertdatetime media table contextmenu paste code'
		],
		toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
	});
</script>
<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>Categoria Ajuda</legend>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" class="form-control input-md">
								<input id="tipo" name="tipo" type="hidden" value="1" class="form-control input-md">
							</div>
						</div>
						<br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
								<button type="submit" id="" name="" class="btn btn-primary">Enviar</button>
							</div>
						</div>
					</fieldset>
				</form>

				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>SubCategoria Ajuda</legend>

						<!-- Select Basic -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="categoria">categoria</label>
							<div class="col-md-4">
								<select id="categoria" name="categoria" class="form-control">

									<?php foreach ($this->atividades as $item): ?>
										<option value="<?php echo $item['idcategoria'] ?>"><?php echo $item['nome'] ?></option>
									<?php endforeach; ?>

								</select>
							</div>
						</div> <br>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" class="form-control input-md">
								<input id="tipo" name="tipo" type="hidden" value="2" class="form-control input-md">
							</div>
						</div><br>

						<!-- Textarea -->
						<div class="form-group">
							<div class="col-md-4">
								<textarea  style="height: 30px; height: 30px" id="descricao" name="descricao"  rows="10" cols="10">&lt;p&gt;Descrição.&lt;/p&gt;</textarea>

							</div>
						</div>
<br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
								<button type="submit" id="" name="" class="btn btn-primary">Enviar</button>
							</div>
						</div>

					</fieldset>
				</form>
			</div>

			<div class = "col-lg-12">
				<table class="table table-hover table-inverse">
					<thead>
					<tr>
						<th>#</th>
						<th>Nome</th>
						<th>Descrição</th>

						<th>Ação</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($this->atividades as $item): ?>
						<tr>
							<th scope="row"><?php echo $item['idcategoria'] ?></th>
							<td><?php echo $item['nome'] ?></td>
							<td><button class="btn-warning"> CATEGORIA</button></td>
							<td><a href="ajuda/excluir/id/<?php echo $item['idcategoria'];?>"><button type="button" class="btn btn-danger" onclick="return confirm('Deletando a categoria as subcategorias serão todas deletadas');"">Excluir</button></a></td>
						</tr>

						<?php foreach ($this->atividades1 as $item1): ?>
							<?php if ($item1['categoria_idcategoria'] == $item['idcategoria']){?>
								<tr>
									<th scope="row"><?php echo $item['idcategoria'] ?>.<?php echo $item1['idtipo'] ?></th>
									<td><?php echo $item1['nome'] ?></td>
									<td><?php echo substr($item1['descricao'], 0, 20); ?>...</td>
									<td><a href="ajuda/excluir/id/<?php echo $item1['idtipo'];?>/tipo/2"><button type="button" class="btn btn-danger">Excluir</button></a>
										<a href="ajuda/editar/id/<?php echo $item1['idtipo'];?>/tipo/2"><button type="button" class="btn btn-dark">Editar</button></a>
									</td>
								</tr>
							<?php } ?>


						<?php endforeach; ?>
					<?php endforeach; ?>

					</tbody>
				</table>


			</div>
		</div>
	</div>
</div>