<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Contatos Institucionais</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-3">
            <form action="" role="form" class="search-form" id="form" method="post">

                <div class="form-group has-feedback">
            		<label for="search" class="sr-only">Pesquisar</label>
            		<input type="text" class="form-control" name="search" id="search" placeholder="Pessoa, instituição, mantenedora, cidade...">
              		<span class="glyphicon glyphicon-search form-control-feedback"></span>
            	</div>
            </form>
        </div>
    </div>
</div>


<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <!--<<th>Telefone</th>->>
      <!--<<th>Email</th>--> 
 
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->contatos as $item):  ?>
                <tr>
                    <td><br><b>Nome: <?php echo $item['nome'] ?></b></br>
                        <br>Instituição: <?php echo $item['nomeinstituicao'] ?></br>
                        <br>Mantenedora: <?php echo $item['nomemantenedora'] ?></br></br>
          

                        <a class="btn btn-small btn-info" href="/contatos/index/expandir/id/<?php echo $item['cod_pessoa'] ?>">
                        Expandir
                    </a>
                      <a class="btn btn-small btn-success" href="/contatos/index/favoritar/id/<?php echo $item['cod_pessoa'] ?>">
                        Favoritos!
                    </a>
                        <a class="btn btn-small btn-primary" href="/contatos/index/expandir/id/<?php echo $item['cod_pessoa'] ?>">
                        Alterar
                    </a>
                        <a class="btn btn-small btn-danger" onclick="return confirm('Você tem certeza que quer excluir este contato?');" href="/contatos/index/excluircontato/id/<?php echo $item['cod_pessoa'] ?>">
                        Excluir
                   
                    </a>
                      </td>
          
                    
                </tr>
            <?php endforeach; ?>
  </tbody>
</table>