<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Instituição</th>
      <th>Mantenedora</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->contatos as $item):  ?>
                <tr>
                  
                    <td><?php echo $item['nome'] ?></td>
                     <td><?php echo $item['nomeinstituicao'] ?></td>      
                     <td><?php echo $item['nomemantenedora'] ?></td> 
                      
                </tr>
            <?php endforeach; ?>
  </tbody>
</table>