
<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Serviços que oferecemos <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>
            <hr>

            <div class="row">

                <?php foreach ($this->atividades as $item): ?>

                    <div class="col-md-3">
                        <a href="#" class="thumbnail">
                            <img src="/static/upload/petshop/<?php echo $item['caminho'] ?>" <?php echo $item['nome'] ?>">
                        </a>
                    </div>

                <?php endforeach; ?>


            </div>






        </div>
    </div>

</section>